name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk to test for code vulnerabilities
        run: snyk code test
        continue-on-error: true

      - name: Run Snyk to test dependencies for vulnerabilities
        run: snyk test
        continue-on-error: true
        
      - name: Upload Snyk report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json
